"""
Conclusion-verified Analogical Schema Induction (CASI)
Part 2: Conclusion Verifier

Checks if the candidate inferences (conclusions) generated by the
SME are logically derivable from the established mapping and the
target case's existing knowledge.
"""

from .schema_mapper import Mapping


class ConclusionVerifier:
    """
    Verifies that candidate inferences are logically derivable.

    This ensures that the analogy is not just a surface match but
    supports the transfer of relational structures in a coherent way.
    """

    def __init__(self, target_knowledge_base: dict | None = None):
        """
        Initialize with the target domain's knowledge base.

        Args:
            target_knowledge_base: A dict representing known facts in the
                                   target domain (e.g., relations, rules).
        """
        self._target_kb = target_knowledge_base or {}
        self._opposites = {"attracts": "repels", "repels": "attracts"}

    def verify_conclusion(self, mapping: Mapping, conclusion: dict) -> bool:
        """
        Verify a single candidate inference (conclusion).

        Args:
            mapping: The Mapping object from the SME.
            conclusion: A candidate inference from the mapping.

        Returns:
            True if the conclusion is derivable, False otherwise.
        """
        if conclusion["type"] != "relation":
            return True  # Not a relational inference, so we don't verify it here

        rel = conclusion["relation"]
        rel_type = rel["type"]
        rel_args = tuple(rel["args"])

        # Check for direct contradictions in the target knowledge base
        if "relations" in self._target_kb:
            for existing_rel in self._target_kb["relations"]:
                existing_args = tuple(existing_rel["args"])
                if existing_args == rel_args:
                    # Contradiction if the types are opposites
                    if self._opposites.get(existing_rel["type"]) == rel_type:
                        return False

        # Check if the relation type is plausible in the target domain
        if "valid_relations" in self._target_kb:
            if rel_type not in self._target_kb["valid_relations"]:
                return False

        return True

    def filter_valid_inferences(self, mapping: Mapping, target_case: dict) -> list:
        """
        Filter the list of candidate inferences to only valid ones.
        For schema extraction, we should not filter out inferences that
        already exist in the target.

        Args:
            mapping: The Mapping object from the SME.
            target_case: The target case data.

        Returns:
            A list of valid candidate inferences.
        """
        if not mapping.candidate_inferences:
            return []

        # In a real scenario, you might filter out inferences that are
        # already known in the target case, but for schema induction,
        # we want to confirm the common structure.
        return [
            conc
            for conc in mapping.candidate_inferences
            if self.verify_conclusion(mapping, conc)
        ]
